name: 'Await Vercel URL'
description:
  'Await Vercel preview URL to run actions after a preview becomes available'
author: 'pine'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  gh_token:
    description: 'The Github Secret'
    required: true
  vercel_project_name:
    description: 'The Vercel project name'
    required: false
  interval:
    description: 'Interval in seconds to check for the URL'
    default: 15
    required: false
  retries:
    description: 'How many times to retry'
    default: 20
    required: false
  delay:
    description: 'Delay in seconds to start checking'
    default: 0
    required: false

# Define your outputs here.
outputs:
  url:
    description: 'The fully qualified deploy preview URL'

runs:
  using: node20
  main: dist/index.js
